# Generated by Django 3.2.6 on 2022-06-02 08:23

from django.db import migrations, models
import django.db.models.manager
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleForTenant2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', timescale.db.models.fields.TimescaleDateTimeField(auto_now_add=True, interval='1 day')),
                ('updated_on', timescale.db.models.fields.TimescaleDateTimeField(auto_now=True, interval='1 day')),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('timescale', django.db.models.manager.Manager()),
            ],
        ),
    ]
