# Generated by Django 3.2.6 on 2022-06-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleForTenant2',
            new_name='ModelForTenant2',
        ),
    ]
